### ISSUE TITLE
Tooltip position appears offset from mouse cursor

### ISSUE THREAD

**Issue by cobyism** [jondavidjohn/bubblechart#1]
Cool project! Just saw your demo page, and it looks like there’s a bug with the positioning of tooltips relative to where the mouse cursor is:

![bubble-bug-1](https://f.cloud.github.com/assets/296432/1332854/a6c5c912-3584-11e3-9b65-c39fc6438c7d.gif)
![bubble-bug-2](https://f.cloud.github.com/assets/296432/1332855/a72b183a-3584-11e3-88cf-75894e31c705.gif)

This was in Google Chrome Stable (Version 30.0.1599.69) on OS X.

**Comment by jondavidjohn** [comment]
Interesting... Do you happen to be on a HiDPI (retina) display?

I've got code to attempt to handle the rendering crisp on HiDPI, but I suspect the scaling dimensions throws off the reported cursor position.  Don't have any equipment to test the HiDPI interactivity currently :confused:

**Comment by cobyism** [comment]
Ah yes, I’m on a retina MBP—that’d explain it. :+1:

**Comment by jondavidjohn** [comment]
@cobyism On an unrelated note, how did you generate those gifs?  Seems like an really great way to demonstrate things.

**Comment by cobyism** [comment]
@jondavidjohn I record using QuickTime’s built-in screen recording functionality, and then use an app called [GIF Brewery](http://gifbrewery.com/) to edit the recorded movie into a GIF as I want it (cropping, length, annotations, speed, framerate vs. colour depth vs. size and so forth). We use that combination for most of the GIFs we post to the GitHub.com blog when we announce new features we want to illustrate, and it works pretty well for us! :smiley:

**Comment by jondavidjohn** [comment]
This bug likely lies somewhere in this section

https://github.com/jondavidjohn/bubblechart/blob/master/src/classes/BubbleChart/Pointer.coffee#L43-L70

I attempted to account for retina displays, but like I said, I don't really have the equipment handy to test/debug it thoroughly.

**Comment by cobyism** [comment]
Just found a possibly relevant excerpt of [this article](http://www.html5rocks.com/en/tutorials/canvas/hidpi/):

> ## Implementation Differences
> 
> On a HiDPI device such as a Macbook Pro with Retina display, Safari 6 carries a webkitBackingStorePixelRatio value of 2 and a devicePixelRatio of 2 whereas Chrome uses a webkitBackingStorePixelRatio value of 1 and a devicePixelRatio of 2.

It goes on to explain about blurry rendering in chrome because of the way it scales things back up for display, another symptom I notice when I view this in Chrome—and then even has some example code for computing the correct backing storage ratio:

``` js
var ...

// finally query the various pixel ratios
devicePixelRatio = window.devicePixelRatio || 1,
backingStoreRatio = context.webkitBackingStorePixelRatio ||
                            context.mozBackingStorePixelRatio ||
                            context.msBackingStorePixelRatio ||
                            context.oBackingStorePixelRatio ||
                            context.backingStorePixelRatio || 1,
ratio = devicePixelRatio / backingStoreRatio;
```

Which might be how you need to adjust things at [this line](https://github.com/jondavidjohn/bubblechart/blob/master/src/classes/BubbleChart/Pointer.coffee#L46) to get it to work :smile: Sorry I don’t have more time right now to have a crack at debugging this for you on my screen, but hopefully that article might lead you work out a solution without needing a retina screen.

**Comment by jondavidjohn** [comment]
Thanks for the detective work in any case.  I'll give this a run tonight and hijack a co-workers Retina MBP tomorrow when they aren't looking. :wink: 

Cheers!

**Comment by cobyism** [comment]
:metal:

**Comment by jondavidjohn** [comment]
Hah, thanks.  I've updated the project page to use the new code, seems to be working fine.

**Comment by cobyism** [comment]
Awesome, yeah the tooltip thing is completely fixed when viewed on my retina here. :+1: 

Possibly related, are these images meant to be so small inside the circles?

![2013-10-18 at 6 03 pm](https://f.cloud.github.com/assets/296432/1362320/653cd8c4-3817-11e3-9941-c42be186d244.png)

Looking at this compared to my GIFs at the top of this thread, it would seem that a side effect of your changes means that they’re all getting displayed at the same size. Is this intended?

**Comment by jondavidjohn** [comment]
In taking a more robust and complete run at retina support I decided that unless explicit `@2x` images are provided (meaning we'll shrink them by 2 always).  It'll prefer small clear images to full size and fuzzy.  So if retina, it shrinks the images down to maintain the clarity.

**Comment by cobyism** [comment]
:cool: Sounds like a good way of handling it!
